backend/apps/owasp/api/search/project.py
backend/apps/owasp/templates/search/project.html

This PR addresses Issue #10 
Screenshot of the change:
Please feel free to suggest different phrasing for the placeholder text, or any other feedback :) 
**Question:** This change has only been made to the `Projects` page. The placeholder in the `Contribute` page search box also says "Search for a project to contribute to...". Perhaps we need to reword that sentence to be more generic (since people might search for keywords in an issue as well?)

Add Total Count Of Projects To Search Bar Placeholder

---

README.md
frontend/src/components/ActionButton.tsx
frontend/src/components/Card.tsx
frontend/src/components/DisplayIcon.tsx
frontend/src/components/TopicBadge.tsx

Updated styles for Card component to work better with dark mode:
- Moved leaders of the project to be lower on the card, after the summary.
- Added borders to blocks with number of forks/stars/contributors.
- Updated labels to have different background color based on type - language or topic.
Updated README file.

Update Card component styles

---

backend/Makefile
frontend/prettier.config.js
frontend/src/components/Card.tsx
frontend/src/components/DisplayIcon.tsx
frontend/src/pages/Projects.tsx

Updated styling and layout for the project labels and contribute button in the Card component:
- wrapped labels into a separate div
- aligned Contribute button with the labels div to always be at the same spot and not be dependent on labels
- added conditional rendering for the whole labels div and for separate sub-divs (languages, topics, social media) so that there's no empty space at the bottom of the card if labels are missing
- increased bottom-padding in DisplayIcon component
- Decreased border-radius for DisplayIcon border

Update Card labels and contribute button layout.

---

frontend/__tests__/src/pages/Chapters.test.tsx
frontend/__tests__/src/pages/Committees.test.tsx
frontend/__tests__/src/pages/Projects.test.tsx
frontend/src/components/Search.tsx

Resolves #261 
This PR adds a default focus to the search input field when the page loads.
Users can start typing immediately without clicking on the search bar. 
Thank You!

Add default focus on search input when page loads

---

backend/apps/owasp/api/search/chapter.py
backend/apps/owasp/api/search/committee.py
backend/apps/owasp/api/search/issue.py
backend/apps/owasp/api/search/project.py
backend/settings/urls.py
backend/tests/owasp/api/search/chapter_tests.py
backend/tests/owasp/api/search/committee_tests.py
backend/tests/owasp/api/search/issue_tests.py
backend/tests/owasp/api/search/project_tests.py

Resolves #254 
Removed unnecessary search API endpoints.
Since the API is used by Slack app for the commands, hence the search files are kept as it is.

Removed owasp search api endpoints

---

frontend/src/components/ActionButton.tsx

fixes #408 
fixed button background color on hover in dark-mode at five end-points:
1. /contribute
2. /projects
3. /projects/'project-name'
4. /chapters
5. /chapters/'chapter-name'
https://github.com/user-attachments/assets/c2ca567c-da1c-4b2a-886b-20b67f8e9a8d

fixed: button-bgcolor-on-hover

---

frontend/src/components/UserCard.tsx

pop-up effect on userCard hover

---

.github/workflows/sync-nest-data.yaml

Resolves #661 
added a condition that checks whether the repo is the OWASP/Nest or not and also the branch is main or not, this ensures that the sync will only be done in the main repo and main branch and not on the forks, which resolves the issue :)

Update : sync jobs now run on main repo and main branch only

---

schema/project.json
schema/tests/data/project/negative/audience-empty.yaml
schema/tests/data/project/negative/audience-invalid.yaml
schema/tests/data/project/negative/audience-missing.yaml
schema/tests/data/project/negative/level-invalid.yaml
schema/tests/data/project/negative/name-empty.yaml
schema/tests/data/project/negative/name-none.yaml
schema/tests/data/project/positive/code-incubator.yaml
schema/tests/project_test.py

Resolves #687 
Added `audience` attribute to the `project.json` file, also added positive and negative test cases to test the schema file.

audience attribute with test case

---

.pre-commit-config.yaml
backend/poetry.lock
backend/pyproject.toml

Resolves #717 
- As we know that isort + more of the precommit already replaced by the ruff
- for reference: [plone discussion](https://community.plone.org/t/drop-black-isort-flake8-and-use-ruff/16413)
- for reference official - [ruff](https://docs.astral.sh/ruff/)
[Screencast from 03-02-25 04:17:32 PM IST.webm](https://github.com/user-attachments/assets/1f35b54c-95f1-4eb8-86c0-1b18d2ec7af5)

fixed pre-commit and  removed i-sort

---

schema/project.json
schema/tests/data/project/negative/blog-none.yaml
schema/tests/data/project/negative/blog-url-invalid.yaml
schema/tests/data/project/positive/optional-properties.yaml
schema/tests/project_test.py

Resolves #(694)
I've added the 'blog' attribute to the project schema with the appropriate validations. I chose 'blogUrl' as the name, but please let me know if it needs to be changed or if any other changes need to be made.

Add blog to project schema

---

frontend/src/components/Card.tsx
frontend/src/components/DisplayIcon.tsx
frontend/src/pages/Projects.tsx
frontend/src/utils/data.ts
frontend/src/utils/utility.ts

fixes: #651 
https://github.com/user-attachments/assets/252a06d7-18d1-4c60-a4dc-6145b86ec9b2

Update card layout

---

frontend/src/components/MetadataManager.tsx

Resolves #615 
hey ark , i thought /img/owasp_icon_white_background.png would be enough to get the image in meta tag but it looks like we need to provide the whole url to the image.
we can use github url of image or we can use our website public image whatever you prefer i have added our website origin ur.
if you'd like to have github link of the image we can do that too .
for this pr, i have fixed image url with the public image url of our website.

fixed image not rendering in the links preview

---

cspell/custom-dict.txt
frontend/public/robots.txt

fixed robot txt to allow scrapper facebook or twitter

---

schema/project.json
schema/tests/data/project/negative/demo-empty.yaml
schema/tests/data/project/negative/demo-invalid.yaml
schema/tests/data/project/negative/demo-non-unique.yaml
schema/tests/data/project/negative/demo-null.yaml
schema/tests/data/project/positive/optional-properties.yaml
schema/tests/project_test.py

Resolves #778
**Make demo field consistently use array type**
**Changes**:
1. Modified the schema to make the demo field always use an array type for URLs
2. Updated corresponding test cases to align with the new array-only format
3. Removed the oneOf validator to simplify the schema structure
**Why**:
This change standardizes how demo URLs are handled in the schema, making it more consistent and easier to validate. Previously, the schema allowed for potential confusion with null values. Now, it will always expect an array of URIs, simplifying both the schema and how consumers handle this field.
**Testing**:
Updated demo-null.yaml test case
Verified that existing valid demo URLs continue to work
Confirmed array validation works as expected

Updated the test cases and Extended the demo Schema

---

frontend/src/components/SortBy.tsx

Fixes Issue #910 
Fixed the "Sort By" text not triggering dropdown options on click.

Fixed sort button not triggering dropdown

---

CONTRIBUTING.md

Make the guidelines about the issues more detailed for contributors.

Add more guidlines to the CONTRIUBITING.md.

---

frontend/src/components/Card.tsx
frontend/src/components/ContributorAvatar.tsx

Resolves #1058
This PR resolves an issue where tooltips would behave incorrectly if the same contributor appeared in multiple cards. The fix appends a unique identifier to the tooltip id, ensuring each tooltip instance is distinct.
1. Added a uniqueKey prop to ContributorAvatar.
2. Modified the tooltip id to include uniqueKey.
3. Updated parent component usage to pass a unique identifier.
https://github.com/user-attachments/assets/fb1ff195-e5b5-44c7-8d19-3194e2fce785

Fix tooltip conflicts for duplicate contributors

---

frontend/src/components/UserCard.tsx
frontend/src/pages/Users.tsx
frontend/src/types/card.ts

Resolves #1068 UI Improvement: The name overflows the div container. 
Here's the corrected version of the usercard:

Issue resolved : #1068 Correction to overflow of name in usercard 

---

README.md

This PR adds a new badge labeled **"CREATED: AUG, 2024"** at the bottom of the existing badge section. This helps in clearly indicating when the project or repository was created.
Changes Introduced : 
1. Added a new badge with the text "CREATED: AUG, 2024"
2. Positioned it at the bottom of all existing badges
3. Ensured styling remains consistent with the other badges
Related Issue
Resolves #1187

added created badge in README.md

---

frontend/src/components/Modal.tsx

Resolves #1193
- Previously, when opening the modal, the close button was automatically focused. After this fix, it will only be highlighted when hovered. Here is a recording clip for reference.
- 
https://github.com/user-attachments/assets/bf35949c-d8cc-49e4-be34-2ade00046d71

fixed the modal window where the close button was focused earlier

---

.github/workflows/run-ci-cd.yaml

Added Trivy scan in CI/CD pipeline

---

README.md

Added black Owasp Nest icon for light theme in Github

Add black icon for light theme in GitHub

---

frontend/src/index.css

fixes: #1221 
current colour :
After changing:

Changed text selection colour for dark mode

---

frontend/docker/Dockerfile

updated dockerfile

---

frontend/src/components/LeadersList.tsx
frontend/src/components/RecentReleases.tsx

fixed frontend  ui bugs

---

frontend/docker/Dockerfile
frontend/next.config.ts

Resolves large size of the docker image for Nextjs based 
frontend. 
1. Automatic copying of traced files to standalone folder by enabling it in next.config.ts
Ref: https://nextjs.org/docs/pages/api-reference/config/next-config-js/output#automatically-copying-traced-files
- Next.js  automatically creates a standalone folder that copies only the necessary files for a production deployment including select files in node_modules.
- Reduces the size by 10x 
- Reduces build time by 5x
2. Added non-root users
3. Added multi-stage docker image with build and run stage as final image
Referenced the [repo](https://github.com/vercel/next.js/tree/canary/examples/with-docker#using-docker) for constructing optimized nextjs app docker image :

Optimize frontend docker image 

---

frontend/src/components/RecentReleases.tsx

Added clickable repository links in the Recent Releases block on the main page.
Links navigate to /repositories/[repositoryName], with repository names converted to lowercase for consistency.

Added a link to the repository name that navigates to /repositories/

---

cspell/custom-dict.txt
frontend/__tests__/unit/utils/slugify.test.ts
frontend/src/app/page.tsx
frontend/src/components/AnchorTitle.tsx
frontend/src/components/CardDetailsPage.tsx
frontend/src/components/RecentIssues.tsx
frontend/src/components/RecentPullRequests.tsx
frontend/src/components/RecentReleases.tsx
frontend/src/components/TopContributors.tsx
frontend/src/utils/slugify.ts

Resolves #1430
This PR improves the `AnchorTitle` component by simplifying its props.  
Previously, `AnchorTitle` accepted both `title` and `href` props. However, since the `href` can be consistently derived from the `title`, we no longer require `href` to be passed manually.
- **Removed** the `href` prop from `AnchorTitle`.
- **Added** logic to automatically generate the `href` by slugifying the provided `title`.
- **Updated** related usage and tests accordingly.
- **Cleaned up** an old TODO left in the code regarding this exact enhancement.
- Reduces the surface area of the component's API.
- Prevents potential mismatches between `title` and `href`.
- Aligns with the original design intention captured in the TODO comment.
- Improves maintainability and developer experience.

Improved AnchorTitle component used slug to get href from title

---

backend/apps/slack/commands/events.py
backend/apps/slack/templates/events.jinja
backend/apps/slack/utils.py
backend/tests/apps/slack/commands/events_test.py
frontend/src/server/queries/homeQueries.ts

Resolves #1427 
Refactored nest bot `/events` command to display info same as main page

Nestbot /events command refactor

---

frontend/__tests__/e2e/pages/Projects.spec.ts
frontend/__tests__/unit/components/BreadCrumbs.test.tsx
frontend/__tests__/unit/pages/Chapters.test.tsx
frontend/__tests__/unit/pages/Projects.test.tsx
frontend/src/app/about/page.tsx
frontend/src/app/snapshots/[id]/page.tsx
frontend/src/app/snapshots/page.tsx
frontend/src/components/BreadCrumbs.tsx
frontend/src/components/CardDetailsPage.tsx
frontend/src/components/SearchPageLayout.tsx

Fixed breadcrumb styling and added tests

---

backend/docker/Dockerfile.local
frontend/docker/Dockerfile.local

Improve APK cache handling in docker

---

CONTRIBUTING.md

Docs Update: Added Next.js to the tech stack section as the project has recently been migrated to Next.js, but the documentation had not been updated to reflect this change. Keeping the docs in sync with the current implementation ensures clarity for new contributors and accurate project representation.

docs: add Next.js to tech stack after migration

---

backend/tests/apps/core/api/csrf_test.py

Resolves #1563
This a child pr which covers the coverage of `csrf.py` which is a part of the parent backend coverage issue.

Add test coverage for `csrf.py`

---

frontend/src/components/CardDetailsPage.tsx

Fixed inactive label alignment on the DetailsCard.
Before and after:

Fix inactive label alignment

---

backend/pyproject.toml

Added concise explanations as comments to each item in the `ruff` lint `ignore` list. This improves code clarity and maintainability for future developers.
Resolves  #1739
Added comments to the `ignore` list within the `tool.ruff.lint` section, explaining the purpose of each ignored Ruff rule. This enhances the clarity of `pyproject.toml` regarding linting configurations.
* **Note on local tests:** `make check` passed successfully. However, `make test` failed locally with a `TLS handshake timeout` / `EOF` error when trying to pull the `mcr.microsoft.com/playwright` Docker image. This appears to be an environmental issue specific to my local machine's network/Docker setup and not related to the code changes in this PR. I expect the CI pipeline to pass these tests on the project's build …

Add explanations for Ruff lint ignore 

---

backend/pyproject.toml

Updated the `[tool.ruff.lint.per-file-ignores]` section in `backend/pyproject.toml` to include direct links to the Ruff documentation for each ignored rule.
Resolves #1770
This change aims to enhance the maintainability and clarity of the Ruff linting configuration by providing immediate access to the official documentation for each specific rule being ignored on a per-file basis.

feat: Enhance Ruff per-file ignores with documentation links

---

backend/tests/apps/github/admin/issue_test.py
backend/tests/apps/github/admin/pull_request_test.py
backend/tests/apps/github/admin/repository_test.py

This PR introduces unit tests for several ModelAdmin classes in `apps/github/admin/` to increase test coverage from 0%.
Resolves #1795 
**Added New Test Files:** Created `tests/apps/github/admin/issue_test.py`, `pull_request_test.py`, and `repository_test.py`.
**Implemented Unit Tests:** Wrote tests for the custom methods (`custom_field_title`, `custom_field_github_url`) found in `IssueAdmin`, `PullRequestAdmin`, and `RepositoryAdmin`.
**Used Mocking:** The tests use `unittest.mock.MagicMock` to simulate Django model objects. This ensures the tests are fast and do not require a database connection, following best practices for unit testing.
New test coverage status

Add unit tests for GitHub admin files

---

backend/tests/apps/ai/common/utils_test.py

This PR introduces unit tests for utils in `apps/ai/common` to increase test coverage from 0%.
Resolves #1794 
Added New Test Files: Created `tests/apps/ai/common/utils_test.py`
Improved the test coverage

Add unit test for ai common files

---

frontend/__tests__/unit/components/Footer.test.tsx

Resolves #1810 
Added Unit Tests for Footer Component
Added comprehensive test suite with 22 test cases covering:
- Renders successfully with minimal required props
- Conditional rendering logic
- Prop-based behavior – different props affect output
- Event handling – simulate user actions and verify callbacks
- State changes / internal logic
- Default values and fallbacks
- Text and content rendering
- Handles edge cases and invalid inputs
- Accessibility roles and labels
- DOM structure / classNames / styles

Fix #1810: Added tests for <Footer> component

---

frontend/__tests__/unit/components/ProjectsDashboardNavBar.test.tsx

Resolves #1921 
This pull request introduces comprehensive unit tests for the ProjectsDashboardNavBar component, which previously had no test coverage. The goal is to improve overall code quality and ensure the component's navigation logic is reliable.
Changes Made:
1. Added Test Suite: Created a new test file at frontend/__tests__/unit/components/ProjectsDashboardNavBar.test.tsx.
2. Test Coverage: The new tests verify the following key behaviors:
3. The component renders successfully without errors.
4. Both "Overview" and "Metrics" navigation links are displayed with the correct href attributes.
5. The correct link is marked as active with the aria-current="page" attribute based on the current URL path.
6. No links are marked as active when the URL path is unrelated.
- [x ] I've read and …

test: Add unit tests for ProjectsDashboardNavBar component

---

frontend/__tests__/unit/components/Modal.test.tsx

Resolves #1859 
Added Unit Tests for Modal Component
Added comprehensive test suite covering:
- Renders successfully with minimal required props
- Conditional rendering logic
- Prop-based behavior – different props affect output
- Event handling – simulate user actions and verify callbacks
- State changes / internal logic
- Default values and fallbacks
- Text and content rendering
- Handles edge cases and invalid inputs
- Accessibility roles and labels
- DOM structure / classNames / styles

Fix #1859: Added test to Modal Component

---

frontend/__tests__/unit/components/SkeletonBase.test.tsx

Resolves #1913
Added comprehensive unit tests for the `SkeletonBase` component to ensure robust behavior and maintain code quality standards.
- **New test file**: `SkeletonBase.test.tsx` with 35+ comprehensive test cases
- **Full coverage** of all component functionality and edge cases
- **Mock implementations** for all external dependencies
- Basic rendering and conditional logic for all `indexName` values
- Component switching between CardSkeleton, UserCardSkeleton, and LoadingSpinner
- Proper prop configurations for each skeleton type
- Null/undefined inputs and empty strings
- Special characters and very long strings
- Case-sensitive indexName handling
- Fallback behavior to LoadingSpinner
- DOM structure and CSS class verification
- Accessibility and screen reader compatibility
- …

test: add comprehensive unit tests for SkeletonBase component

---

backend/apps/common/model_fields.py
backend/apps/nest/clients/kms.py
backend/tests/apps/nest/clients/kms_test.py

Use singleton pattern in kms client

---

frontend/src/app/layout.tsx

Resolves #2033 
Footer sticks to bottom when screen height is over 1100px

fix: align footer to bottom

---

frontend/jest.setup.ts
frontend/package.json
frontend/pnpm-lock.yaml

Resolves #2353
1. Update TypeScript version to 5.9 in `package.json`.
2. Run `pnpm install` to update `pnpm-lock.yaml`
3. Fix TypeScript 5.9 compatibility by removing the TextEncoder polyfill (native in Node.js 18+) in `jest.setup.ts`
4. Verify build and type checking pass.

enhancement/Migrate frontend to TypeScript 5.9

---

frontend/src/components/SortBy.tsx

- Remove blue outline and inconsistent hover backgrounds
- Add proper focus/active states styles to match the design system
- Improve light/dark mode theme integration
- Fix trigger background blending issues
Fixes #1372
Before Changes:
| Light Mode | Dark Mode |
|--------|--------|
| <img width="348" height="223" alt="image" src="https://github.com/user-attachments/assets/62801042-4b48-401f-9fd8-80fff72f442d" /> | <img width="327" height="225" alt="image" src="https://github.com/user-attachments/assets/f44b1ef6-b21a-43bd-acc6-5039a265a9b5" /> |
| <img width="351" height="274" alt="image" src="https://github.com/user-attachments/assets/598593f5-375d-4d00-a808-3f41b42d1378" /> | <img width="310" height="263" alt="image" src="https://github.com/user-attachments/assets/c4f2ae4e-f5f5-4f93-a38e …

fix: improve Sort By dropdown styling consistency
