OWASP/Nest

- Makefile
- backend/apps/common/constants.py
- backend/apps/common/management/commands/clear_cache.py
- backend/apps/owasp/api/search/issue.py
- backend/apps/owasp/api/search/project.py
- backend/apps/owasp/constants.py
- backend/settings/base.py
- Added cache logic to project.py and issue.py to retrieve search queries from the local memory cache system instead of sending repeated queries to algolia which helps in the problem of limited number algolia search queries.
- added CACHES dir to base.py to reconfigure the global settings of project.
- this refers to Issue #6 
- System: Linux/GNU Kali Rolling
> Implement Indexed entities cache

- backend/Dockerfile.local
- backend/Dockerfile.staging
- backend/Dockerfile.test
- backend/poetry.lock
- backend/pyproject.toml
Update to the latest Python version.
> Bump docker files Python to 3.13

- backend/apps/owasp/templates/search/chapters.html
- backend/settings/urls.py
- backend/templates/base.html
PR for add Chapters Page to OWASP Nest [(#29 )](https://github.com/OWASP/Nest/issues/29)
> Add chapters page

- backend/apps/owasp/api/search/chapter.py
- backend/apps/owasp/models/chapter.py
- backend/apps/owasp/templates/search/chapter.html
Resolved the merge conflicts, hope this works
> Add Total Count Of Chapters To Search Bar Placeholder

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/main.tsx
- frontend/src/pages/Home.tsx
I have set up the BrowserRouter in main.tsx.
For now, I have created a Home page, which can be accessed at http://localhost:3000/.
In the future, additional pages can be created using similar code, as shown in the screenshot.
> Add React routing

- Makefile
- backend/apps/common/index.py
- backend/apps/common/management/commands/algolia_update_synonyms.py
- backend/apps/github/index/issue.py
- backend/apps/github/index/synonyms/issues.json
- backend/apps/owasp/index/project.py
- backend/apps/owasp/index/synonyms/projects.json
- backend/settings/base.py
Resolves #87 
- Implement Algolia index synonyms
- Add some Issue and Project index synonyms
> Implement index synonyms

- .github/workflows/ci-cd.yaml
- frontend/src/components/Card.tsx
- frontend/src/pages/Projects.tsx
Resolves #150 
Modified Card and Project component a bit to resolve errors thrown in test job in pipeline
> Added indexes to ensure unique key props

- backend/apps/common/management/commands/add_project_custom_tags.py
- backend/data/project-custom-tags/gsoc-2020.json
- backend/data/project-custom-tags/gsoc-2021.json
- backend/data/project-custom-tags/gsoc-2022.json
- backend/data/project-custom-tags/gsoc-2023.json
close #167 
- Added JSON files for GSoC project custom tags for the years 2020–2023.
- Files are located in `backend/data/project-custom-tags/`.
> Add GSoC JSON files for 2020-2023 with custom tags

- frontend/__tests__/src/App.test.tsx
- frontend/__tests__/src/data/mockChapterData.ts
- frontend/__tests__/src/pages/Chapters.test.tsx
- frontend/src/App.tsx
- frontend/src/pages/Chapters.tsx
- frontend/src/pages/index.ts
Resolves #90 
This pull request introduces a new "Chapters" page to the application.
> Implement Chapters Page

- README.md
Made changes in readme for troubleshooting in windows as suggested by @arkid15r
> Doc: troubleshoot for windows

- frontend/src/components/Card.tsx
fixes #213 
changes in the key during map to make sure it is unique
> fix: the key issue

- frontend/__tests__/src/pages/Committees.test.tsx
- frontend/src/components/Pagination.tsx
- frontend/src/pages/Committees.tsx
added additional logic for rendering only when there is more than 1 page
fixes #214
> fix: changes in pagination logic

- frontend/__tests__/src/pages/Chapters.test.tsx
- frontend/__tests__/src/pages/Committees.test.tsx
- frontend/__tests__/src/pages/Projects.test.tsx
- frontend/src/components/Search.tsx
- frontend/src/components/SearchPageLayout.tsx
- frontend/src/lib/hooks/useSearchPage.ts
- frontend/src/lib/test-util.tsx
- frontend/src/pages/Chapters.tsx
- frontend/src/pages/Committees.tsx
- frontend/src/pages/Projects.tsx
Resolves https://github.com/OWASP/Nest/issues/198
I have added a feature to use the URL query for search, optimized the code for reusability, and created a custom hook for the search functionality.
> added search query part and made code optimised

- README.md
Resolves #177 
added instruction .
> add instruction in readme.md

- frontend/__tests__/src/pages/Chapters.test.tsx
- frontend/__tests__/src/pages/Committees.test.tsx
- frontend/__tests__/src/pages/Projects.test.tsx
- frontend/src/components/SearchPageLayout.tsx
Resolves #215 
Correct positioning of Search component solves the weird appearance .
> synced search bar with data appearances

- frontend/__tests__/src/pages/Chapters.test.tsx
- frontend/__tests__/src/pages/Committees.test.tsx
- frontend/__tests__/src/pages/Home.test.tsx
- frontend/src/pages/Home.tsx
closes #229
**Checklist**
- Added client-side redirection logic.
- Updated unit tests to cover the redirection functionality.
- Verified functionality locally.
> Added temporary redirection from / to /projects

- CONTRIBUTING.md
Resolves pre-commit not installed error
Added command to install pre-commit in the prerequisites
> Added pre-commit installation in prerequisites

- CONTRIBUTING.md
Added instructions to update Algolia app key, id in frontend environment in the contribution.md.
> added algolia key setup for frontend in CONTRIBUTING.md

- frontend/src/components/SearchPageLayout.tsx
Resolves #262 
----
https://github.com/user-attachments/assets/27a33b9a-0ffc-4fc9-8dd2-5dba47eff166
> Fix search bar component behaviour

- frontend/src/components/Card.tsx
Resolved issues with missing padding between card elements.
> Missing padding in Card elements

- frontend/src/components/Search.tsx
- impleted the debouncing cleanup logic
- increase the debouncing timeout from 500ms to 750ms
> Fix : SearchBar unexpected behaviour

- frontend/global.d.ts
- frontend/tsconfig.json
Resolves #272 
fixes for absolute import in vs code
> fixes-absolute import

- .github/labeler.yml
- .github/workflows/pr-labeler.yaml
> Add PR labeler

- frontend/Makefile
- frontend/jest.config.ts
- frontend/jest.setup.ts
- frontend/package-lock.json
- frontend/package.json
Resolves #302 
This PR adds SWC which is significantly faster than tsc for transpilation, reducing test execution times and tsc for type-checking.
Improves CI/CD Efficiency by parallel execution of type-checking and tests speeds up pipeline completion.
> Added swc/jest for testing and tsc for type-checking

- frontend/src/components/Footer.tsx
- frontend/src/pages/ChapterDetails.tsx
- frontend/src/pages/CommitteeDetails.tsx
- frontend/src/pages/ProjectDetails.tsx
Resolves #321 
Further comments and suggestions on this PR are welcome.
> fix the footer layout

- backend/apps/github/index/__init__.py
- backend/apps/github/index/release.py
- backend/apps/github/index/repository.py
- backend/apps/github/models/mixins/__init__.py
- backend/apps/github/models/mixins/issue.py
- backend/apps/github/models/mixins/release.py
- backend/apps/github/models/mixins/repository.py
- backend/apps/github/models/release.py
- backend/apps/github/models/repository.py
- backend/apps/owasp/index/chapter.py
- backend/apps/owasp/index/committee.py
- backend/apps/owasp/models/project.py
Add release and repository index, fix minor issues with other entities index.
> Add release and repository index

- backend/apps/core/models/prompt.py
- backend/apps/github/models/issue.py
- backend/apps/owasp/management/commands/owasp_enrich_chapters.py
- backend/apps/owasp/management/commands/owasp_enrich_committees.py
- backend/apps/owasp/management/commands/owasp_enrich_projects.py
- backend/apps/owasp/models/chapter.py
- backend/apps/owasp/models/committee.py
- backend/apps/owasp/models/common.py
- backend/apps/owasp/models/project.py
Simplify  `Prompt` model methods.
> Refactor `Prompt`

- frontend/__tests__/src/pages/UserDetails.test.tsx
- frontend/src/pages/UserDetails.tsx
> fixed: users join date issue

- frontend/src/pages/UserDetails.tsx
> exact-match-users-detail-page #385

- backend/apps/owasp/models/chapter.py
- backend/apps/owasp/models/mixins/chapter.py
- backend/apps/slack/commands/__init__.py
- backend/apps/slack/commands/chapters.py
- backend/apps/slack/commands/owasp.py
- backend/tests/slack/commands/chapters_tests.py
- backend/tests/slack/commands/owasp_tests.py
> added /chapters NestBot command

- backend/tests/common/management/commands/algolia_update_synonyms_tests.py
> Increase `common/algolia_update_synonyms` command test coverage

- backend/tests/common/management/commands/algolia_update_suggestions_tests.py
> increase common `algolia_update_suggestions` command test coverage

- backend/tests/owasp/scraper_tests.py
Resolves #414 
this issue icrease tesr case code coverage from 21% to 91%
> coverage owasp/scraper 21->91

- frontend/components.json
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Footer.tsx
- frontend/src/components/Pagination.tsx
- frontend/src/components/ui/Toast.tsx
> lucide react removed

- frontend/src/sentry.config.ts
Resolves #475  
made the necessary changes to unmask the text in sentry replays, let me know if changes are required especially if we need to mask any of the sensitive information
> update : sentry replay text unmasked

- backend/apps/github/index/user.py
> algolia-index-for-user-page

- .github/workflows/ci-cd.yaml
Resolves #476
Implement versioning in frontend and backend images by appending build date and commit hash to Docker tags for better tracking.
> Make staging release version more informative

- frontend/src/components/ChapterMap.tsx
> fixed-overlapping-issue

- frontend/src/components/ChapterMap.tsx
> Revert "fixed-overlapping-issue"

- CONTRIBUTING.md
> fixed docs

- backend/apps/github/graphql/nodes/repository.py
- backend/apps/github/models/repository.py
- backend/apps/owasp/graphql/nodes/project.py
- backend/tests/github/graphql/nodes/repository_test.py
- backend/tests/owasp/graphql/nodes/project_test.py
- frontend/src/api/queries/projectQueries.ts
- frontend/src/components/CardDetailsPage.tsx
- frontend/src/components/RelatedRepositoriesCard.tsx
- frontend/src/components/RepositoriesCard.tsx
- frontend/src/pages/ProjectDetails.tsx
- frontend/src/types/card.ts
- frontend/src/types/project.ts
Resolves #649 
[Screencast from 02-02-25 04:33:36 PM IST.webm](https://github.com/user-attachments/assets/f913ba74-f59c-4756-b0cf-cd2833bbfc82)
> Added related repository block in the Project Details

- frontend/src/components/DisplayIcon.tsx
> tooltip-bug

- cspell/Makefile
- cspell/custom-dict.txt
> fixed makefile bug 

- frontend/src/components/SortBy.tsx
- frontend/src/hooks/useSearchPage.ts
- frontend/src/pages/Projects.tsx
Resolves #826 
---
This pull request includes changes to improve the user experience by modifying the sorting functionality and default order in the search and projects pages.
Improvements to sorting functionality:
* [`frontend/src/components/SortBy.tsx`](diffhunk://#diff-b1955de76ea3870e960eeb58a0bdf54eb575f26a5581a62d9c89d541adbcf57aL41-R44): Updated the `Sort By` label to be a clickable element, enhancing user interaction.
Changes to default order:
* [`frontend/src/hooks/useSearchPage.ts`](diffhunk://#diff-c933e257d8335a7d737ea3aadd0b4f63a9480b4b2019da3f2ae0fb77b570e00bL48-R48): Changed the default order parameter from 'asc' to 'desc' to improve the relevance of search results.
* [`frontend/src/pages/Projects.tsx`](diffhunk://#diff-82efddf2c9656052173356f601a4c1afc44fa2e2bc55f2cfcfebfa6 …
> Update sorting order to descending and enhance Sort By label styling

- frontend/__tests__/src/pages/Contribute.test.tsx
- frontend/src/hooks/useSearchPage.ts
> fix params logic

- frontend/src/utils/urlIconMappings.ts
Resolves #887
Updates to new twitter icon.
Before:
After:
> fix: new twitter icon

- .github/workflows/run-ci-cd.yaml
- .github/workflows/test-schema.yaml
- CONTRIBUTING.md
- Makefile
- cspell/Makefile
- frontend/Makefile
Added `make test-all` command to run all the tests using one single command instead of running individual test commands.
> Added test-all command

- frontend/src/components/MultiSearch.tsx
Resolves #297 
* can't show the click outside because i am on linux and my cursor isn't  coming on my screencas
[Screencast from 23-02-25 04:02:17 AM IST.webm](https://github.com/user-attachments/assets/c860d3ea-3b98-41ff-a59f-b17188e5553a)
> Added navigation through keys in suggestion in Home 

- backend/Dockerfile.local
- frontend/__tests__/src/data/mockRepositoryData.ts
- frontend/__tests__/src/pages/RepositoryDetails.test.tsx
- frontend/src/components/RepositoriesCard.tsx
- frontend/src/pages/RepositoryDetails.tsx
> Improved counters format consistency

- frontend/__tests__/e2e/pages/home.spec.ts
- frontend/src/components/ItemCardList.tsx
- frontend/src/pages/Home.tsx
- frontend/src/utils/dateFormatter.ts
Resolves #927 
Home page recent issue :
Home page recent releases:
peoject details section:
> fix alignment of issue/release card component

- backend/Makefile
- backend/apps/common/index.py
- backend/apps/owasp/index/project.py
- frontend/src/utils/sortingOptions.ts
> Added updated_at attribute in sortBy component

- CONTRIBUTING.md
Resolves #1017 
Changed the API endpoint at line 127 in CONTRIBUTING.md file to "http://localhost:8000/api/v1/"
> Modified: Updated the API endpoint in contributing.md file

- frontend/src/index.css
Fixes: #1051 
I've fixed the loading spinner for Nest.
> Fixed Loading Spinner

- backend/apps/core/api/algolia.py
- backend/tests/core/api/algolia_test.py
- frontend/src/api/fetchAlgoliaData.ts
> Added facet filters

- backend/apps/owasp/models/common.py
- backend/tests/owasp/models/common_test.py
Resolves #1115
Required Test Cases passed
> Fix regex for chapter leader

- backend/apps/github/management/commands/github_update_owasp_organization.py
- backend/apps/owasp/models/common.py
- backend/tests/owasp/models/common_test.py
Update entity tags parsing logic
> Update entity tags parsing logic

- frontend/__tests__/e2e/pages/Home.spec.ts
- frontend/src/pages/Home.tsx
Cleanup/ Removal of data-testid from code as discussed in Pull request #1137
> Issue resoved: 1182: cleared getTestId

- frontend/src/pages/UserDetails.tsx
Resolves #1219
https://github.com/user-attachments/assets/13d5c7d3-1b23-47ac-9028-7b953de7ff9c
> Removed heatmap for private contributors

- frontend/src/app/layout.tsx
- frontend/src/components/ScrollToTop.tsx
> Added scroll to top

- frontend/src/components/CardDetailsPage.tsx
Resolves #1328 
Updated styling to resolve issue
> updated line break issue

- backend/apps/github/graphql/nodes/repository.py
Fixed the /projects/csrfguard  by making organization optional
> Added organization to return None if it not exist 

- .github/workflows/run-ci-cd.yaml
> Fix flaky tests in CI/CD

- frontend/src/components/Header.tsx
- frontend/src/components/NavButton.tsx
This PR is related to the issue #1608 
I am not sure if this is how you want it to look. I have added a minimum width property but if you want to change how it looks you can message me and I will work on it ASAP.
> Resolved bug: Made header buttons consistent

- backend/apps/github/utils.py
- backend/apps/owasp/scraper.py
- backend/apps/slack/views.py
- backend/docker/Dockerfile.local
- backend/docker/Dockerfile.test
- backend/tests/apps/common/utils_test.py
- cspell/custom-dict.txt
- docs/docker/Dockerfile.local
- frontend/docker/Dockerfile.local
- frontend/docker/Dockerfile.unit.test
- frontend/src/utils/urlIconMappings.ts
- schema/docker/Dockerfile.test
Trying to make SonarCloud happy.
> Fix some security hotspots

- backend/apps/nest/graphql/mutations/user.py
- frontend/__tests__/unit/utils/middleware.test.ts
- frontend/src/app/api/auth/[...nextauth]/route.ts
- frontend/src/components/LoginPageContent.tsx
- frontend/src/components/UserMenu.tsx
Task 
Test case
for fail test case
> Fix test cases and update code

- Makefile
> Fix docker compose command

- backend/apps/common/management/commands/load_data.py
- backend/apps/common/management/commands/restore_backup.py
- backend/apps/core/utils/index.py
- backend/apps/github/management/commands/github_update_owasp_organization.py
- backend/apps/github/management/commands/github_update_related_organizations.py
- backend/tests/apps/common/management/commands/load_data_test.py
- backend/tests/apps/common/management/commands/restore_backup_test.py
- backend/tests/apps/core/utils/index_test.py
- backend/tests/apps/github/management/commands/github_update_related_organizations_test.py
Refactor code to use `index.disable_indexing()` context manager.
> Introduce DisableIndexing context manager

- frontend/__tests__/unit/components/ContributorAvatar.test.tsx
Resolves #1806
This PR implements comprehensive unit tests for the `ContributorAvatar` component, covering all items from the Essential Test Coverage Checklist. The test suite includes 14 test cases that verify component rendering, conditional logic, accessibility features, and edge case handling.
**Key areas covered:**
- Component rendering with required props and correct DOM structure
- Conditional logic testing the `isAlgoliaContributor` function and URL parameter handling  
- Tooltip content generation including contribution counts and display name fallbacks
- Accessibility features with proper alt text and link attributes for screen readers
- Edge case handling for missing data, zero contributions, empty strings, and boundary values
- CSS classes and styling verification for hover …
> feat: Added comprehensive unit tests for ContributorAvatar component

- backend/tests/apps/github/api/internal/queries/issue_test.py
- backend/tests/apps/github/api/internal/queries/milestone_test.py
- backend/tests/apps/github/api/internal/queries/organization_test.py
- backend/tests/apps/github/api/internal/queries/pull_request_test.py
- backend/tests/apps/github/api/internal/queries/release_test.py
- backend/tests/apps/github/api/internal/queries/repository_contributor_test.py
Resolves #1799 
improved coverage to more than 80%
> test: improved coverage of github queries to more than 80

- frontend/__tests__/unit/components/TopContributorsList.test.tsx
Resolves #1917 
Added Unit Tests for TopContributorsList Component
Added comprehensive test suite with 34 test cases covering:
- Renders successfully with minimal required props
- Conditional rendering logic
- Prop-based behavior – different props affect output
- Event handling – simulate user actions and verify callbacks
- State changes / internal logic
- Default values and fallbacks
- Text and content rendering
- Handles edge cases and invalid inputs
- Accessibility roles and labels
- DOM structure / classNames / styles
> Fix #1917 Added tests for TopContributorsList component

- frontend/__tests__/unit/components/UserMenu.test.tsx
Resolves #1918 
Added Unit Tests for <UserMenu> component
- Tested all states: authenticated, unauthenticated, and loading
- Handled edge cases like missing data, rapid clicks, and logout behavior
- Ensured accessibility with proper ARIA attributes and fallbacks
- Mocked next-auth, useLogout, and next/image
- Followed project patterns and React Testing Library best practices
> test: add unit tests for UserMenu component (#1918)

- .coderabbit.yaml
> Add auto review on feature branches to coderabbitai config.

- README.md
> Update README badge links
